application: wunder-finance
version: 2
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: lxml
  version: "2.3"
- name: pycrypto
  version: "2.6"

handlers:
- url: /static/
  static_dir: static

- url: /.*
  script: wunderlist_finance.app
